name: GitHub Release

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            dep_base_dir: /usr/lib/llvm-19
          - target: x86_64-apple-darwin
            os: macos-14
            dep_base_dir: /opt/homebrew/opt/llvm@19
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set env
        run: |
          echo "MLIR_SYS_190_PREFIX=${{ matrix.dep_base_dir }}" >> $GITHUB_ENV
          echo "LLVM_SYS_191_PREFIX=${{ matrix.dep_base_dir }}" >> $GITHUB_ENV
          echo "TABLEGEN_190_PREFIX=${{ matrix.dep_base_dir }}" >> $GITHUB_ENV
      - name: Install deps
        run: make deps && make deps-ci-linux
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cairo-native-compile
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: cairo-native-compile-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cairo-native-dump
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: cairo-native-dump-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cairo-native-run
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: cairo-native-run-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cairo-native-stress
          manifest_path: debug_utils/cairo-native-stress/Cargo.toml
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: cairo-native-stress-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cairo-native-test
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: cairo-native-test-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: starknet-native-compile
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: starknet-native-compile-$target
          token: ${{ secrets.GITHUB_TOKEN }}
